{
    'name': "Ntropy Demo Data",
    'summary': """This module generate demo data based Odoo Mexican localization for testing proposes.""",
    'description': """This module generate demo data based Odoo Mexican localization for testing proposes.""",
    'author': "Alfonso Gonzalez",
    'website': "https://ntropy.tech/odoo",
    'category': 'Customizations',
    'version': '17.4',
    'license': "LGPL-3",
    'sequence': "-100",
    'depends': [
        # Modules
        'base',
        'mail',
        'sale_management',
        # 'sale_subscription',
        'account',
        'crm',
        'stock',
        'stock_barcode',
        'account_accountant',
        'purchase',
        'point_of_sale',
        'project',
        'timesheet_grid',
        'hr_holidays',
        'hr',
        'hr_payroll',
        'hr_attendance',
        # 'helpdesk',
        # 'whatsapp',
        'web_studio',
        # Extra
        'base_automation',
        'account_budget',
        'account_accountant_batch_payment',
        'analytic_enterprise',
        'product',
        'contacts',
        'sale_margin',
        'product_margin',
        'stock_dropshipping',
        'project_account_budget',
        # Mexican localization modules
        'l10n_mx',
        'l10n_mx_edi',
        'l10n_mx_edi_extended',
        'l10n_mx_edi_landing',
        'l10n_mx_edi_pos',
        'l10n_mx_edi_sale',
        'l10n_mx_edi_stock',
        'l10n_mx_edi_stock_extended',
        'l10n_mx_edi_stock_extended_30',
        'l10n_mx_xml_polizas',
        'l10n_mx_reports',
        'l10n_mx_reports_closing',
        'l10n_mx_hr',
        'l10n_mx_hr_payroll',
        'l10n_mx_hr_payroll_account',
    ],
    'data': [
        # Security
        'security/ir.model.access.csv',
        # Wizard
        # Reports
        # Views
        'views/form.xml',
        'views/menu.xml',
        # Data
        'data/demo_companys.xml',
        # 'data/res.config.settings.xml',
        'data/res.lang.xml',
        'data/account.account.csv',
        'data/account.account.xml',
        'data/res.partner.bank.xml',
        'data/account.journal.xml',
        'data/account.tax.group.xml',
        'data/res.partner.category.xml',
        'data/res.partner.xml',
        'data/res.users.xml',
        'data/pos.product.template.xml',
        'data/rest.product.template.xml',
        'data/account.fiscal.year.xml',
        'data/product.pricelist.xml',
        'data/stock.route.xml',
        # 'data/stock.warehouse.xml',
        # Demo Workflows Configurations
        'data/product.category.xml',
        'data/product.template.xml',
        'data/sale.order.template.xml',
        'data/pos.category.xml',
        'data/res.currency.xml',
        'data/account.payment.term.xml',
        'data/l10n.mx.edi.vehicle.xml',
        'data/hr.employee.xml',
        'data/hr.contract.xml',
        'data/hr.leave.xml',
        'data/hr.attendance.xml',
        'data/budgets.xml',
        # Demo Data
        'data/account.move.xml',
        # 'data/account.payment.xml',
        # 'data/cron.xml',
        # 'data/ntropy.xml',
        # Sequence
    ],
    'currency': "USD",
    'price': 0,
    'qweb': [''],
    'images': [''],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
