{
    'name': "Ntropy México Demo Data",
    'summary': """This generates a large number of products, partners, orders, invoices for demonstration.""",
    'description': """This generates a large number of products, partners, orders, invoices for demonstration.""",
    'author': "Alfonso Gonzalez",
    'website': "https://ntropy.tech/odoo",
    'category': 'Customizations',
    'version': '0.3',
    'license': "LGPL-3",
    'sequence': "-100",
    'depends': ['base',
                'mail',
                'sale_management',
                'account',
                'account_accountant',
                'account_budget',
                'purchase',
                'stock',
                'stock_barcode',
                'product',
                'contacts',
                'base_automation',
                'l10n_mx',
                'l10n_mx_edi',
                'l10n_mx_edi_extended',
                'l10n_mx_edi_landing',
                'l10n_mx_edi_pos',
                'l10n_mx_edi_sale',
                'l10n_mx_edi_stock',
                'l10n_mx_edi_stock_extended',
                'l10n_mx_edi_stock_extended_30',
                'l10n_mx_xml_polizas',
                'l10n_mx_reports',
                'l10n_mx_reports_closing',
                'sale_margin',
                'product_margin',
                'analytic_enterprise',
                'stock_dropshipping',
                'account_accountant_batch_payment',
                # Upcooming Modules to incorporate
                # 'point_of_sale',
                'hr',
                'hr_payroll',
                'l10n_mx_hr',
                'l10n_mx_hr_payroll',
                'l10n_mx_hr_payroll_account',
                'hr_holidays',
                'hr_attendance',
                # 'sale_subscription',
                'project',
                'project_account_budget',
                'timesheet_grid',
                # 'helpdesk',
                # 'crm',
                # 'whatsapp',
                'web_studio',
                ],
    'data': [
        # Security
        'security/ir.model.access.csv',
        # Views
        # Wizard
        # Reports
        # Views
        'views/form.xml',
        'views/menu.xml',
        # Data
        'data/res.lang.xml',
        'data/account.account.csv',
        'data/account.account.xml',
        'data/res.partner.bank.xml',
        'data/account.journal.xml',
        'data/account.tax.group.xml',
        'data/res.partner.category.xml',
        'data/base_cfdi.xml',
        'data/pos_company.xml',
        'data/res.partner.xml',
        'data/res.users.xml',
        'data/pos.product.template.xml',
        'data/account.fiscal.year.xml',
        'data/product.pricelist.xml',
        'data/stock.route.xml',
        'data/stock.warehouse.xml',
        # Demo Data Workflows
        'data/product.category.xml',
        'data/product.template.xml',
        'data/sale.order.template.xml',
        # 'data/pos.category.xml',
        'data/res.currency.xml',
        'data/account.payment.term.xml',
        'data/l10n.mx.edi.vehicle.xml',
        'data/hr.employee.xml',
        'data/hr.contract.xml',
        'data/hr.leave.xml',
        'data/hr.attendance.xml',
        # 'data/account.move.xml',
        # 'data/account.payment.xml',
        # 'data/cron.xml',
        'data/ntropy.xml',
        # Sequence
    ],
    'currency': "USD",
    'price': 0,
    'qweb': [''],
    'images': [''],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
